#!/bin/bash

killall -e conky

# For plasma 4
#sleep 1 && feh --bg-fill $(find $(grep wallpaper= ~/.kde/share/config/plasma-desktop-appletsrc | tail -n 1 | cut -d '=' -f 2) -iname "*x*.png" | head -n 1)

# For plasma 5
sleep 1 && feh --bg-fill $(grep -o '/usr/share/wallpapers/Next.*' ~/.config/plasma-org.kde.plasma.desktop-appletsrc)

conky -p 5 -c ~/.conkyrc-$(hostname | cut -d '-' -f 2)
