#!/bin/bash

TEST_DIR="$(pwd)/gitTest"
USER1_MACHINE="$TEST_DIR/user1"
USER2_MACHINE="$TEST_DIR/user2"
CENTRAL_MACHINE="$TEST_DIR/central"
PROJECT_NAME="project"


# Make all directories
mkdir -p $CENTRAL_MACHINE $USER1_MACHINE $USER2_MACHINE
git init --bare $CENTRAL_MACHINE/"$PROJECT_NAME".git
git clone -c user.name="Bastien" $CENTRAL_MACHINE/$PROJECT_NAME $USER1_MACHINE/$PROJECT_NAME
git clone -c user.name="Thomas" $CENTRAL_MACHINE/$PROJECT_NAME $USER2_MACHINE/$PROJECT_NAME

# Initial commit
SAMPLE_TEXT_FILE=a.txt
touch $USER1_MACHINE/$PROJECT_NAME/$SAMPLE_TEXT_FILE
cd $USER1_MACHINE/$PROJECT_NAME \
&& git add $SAMPLE_TEXT_FILE \
&& git commit -am "Initial commit" \
&& echo 'work' >> $SAMPLE_TEXT_FILE \
&& git commit -am "Modify $SAMPLE_TEXT_FILE" \
&& echo -e "#!/bin/bash\n\necho hello" > b.txt \
&& git add -A \
&& git commit -m "Add powerful script" \
&& git push


cd $USER2_MACHINE/$PROJECT_NAME \
&& git pull \
&& git checkout -b featureF master^ \
&& touch featureF_part1.txt \
&& echo -e "\nLigne pour la feature F" >> a.txt \
&& git add -A \
&& git commit -m "Début de la feature F" \
&& git push --set-upstream origin featureF



